In [72]:
import pandas as pd

In [73]:
CFA = pd.read_excel('Final Project Data.xlsx')

In [74]:
CFA

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering
0,1,125836.82,2018.28,7434,1238,6958,15630,NaN,76008,12935.0,19067.0,2197
1,2,126169.87,1931.96,8179,1016,7888,17083,NaN,74817,13882.0,18766.0,1621
2,3,130949.97,1961.31,9309,1087,7695,18091,NaN,79235,12819.0,18002.0,2801
3,4,98556.80,1616.51,5851,454,5438,11743,NaN,60434,10312.0,14509.0,1557
4,5,128648.25,1944.40,7829,871,7137,15837,NaN,78364,14418.0,17617.0,2411
5,6,134611.88,1987.98,8060,1159,8087,17306,NaN,81339,15743.0,17759.0,2465
6,7,137931.66,2058.60,9080,999,7316,17395,NaN,82617,15442.0,17973.0,4504
7,8,98336.56,1475.50,6180,625,5300,12105,NaN,58439,10728.0,15119.0,1946
8,9,111412.63,1739.10,6525,1036,5815,13376,NaN,65663,11527.0,19590.0,1257
9,10,120144.74,1846.63,7646,1015,6812,15473,NaN,75033,10578.0,16980.0,2081
10,11,120890.11,1801.21,7559,1432,6835,15826,NaN,72163,13107.0,18728.0,1065
11,12,124143.74,1855.66,8324,1691,7755,17770,NaN,70682,11939.0,19062.0,4690
12,13,122794.31,1846.58,6449,1264,8852,16565,1801.0,72919,12409.0,17226.0,1875
13,14,117421.37,1789.86,5586,1192,7602,14380,2022.0,72110,12088.0,15032.0,1791
14,15,118343.59,1793.33,5971,883,6958,13812,1639.0,73035,12233.0,16059.0,1559
15,16,122036.56,1814.68,6229,1713,8263,16205,1892.0,72372,12213.0,18075.0,1280
16,17,125188.19,1855.68,6426,1567,7750,15743,2010.0,75848,12769.0,17180.0,1640
17,18,128334.95,1956.06,6677,1406,8419,16502,2377.0,74775,14226.0,16738.0,3718
18,19,127679.69,1897.00,6932,1230,8687,16849,2328.0,78163,12541.0,15314.0,2486
19,20,100793.26,1790.56,148,0,13383,13531,1934.0,85237,NaN,NaN,90
20,21,88279.11,1357.32,0,0,12884,12884,2230.0,72932,NaN,NaN,243
21,22,90827.94,1388.55,0,0,16095,16095,2727.0,71890,NaN,NaN,116
22,23,94278.31,1378.33,0,0,18836,18836,3254.0,71400,NaN,NaN,793
23,24,103772.89,1499.16,0,0,20381,20381,4247.0,78919,NaN,NaN,245
24,25,106622.80,1849.18,0,0,20985,20985,4771.0,80194,NaN,NaN,673
25,26,116115.88,1800.25,0,0,23454,23454,4913.0,86941,NaN,NaN,808
26,27,119367.33,1839.55,0,0,22477,22477,4900.0,91275,NaN,NaN,714
27,28,123036.22,1845.00,0,0,25137,25137,4072.0,93427,NaN,NaN,400
28,29,149466.31,1920.10,0,0,33563,33563,8749.0,105435,NaN,NaN,1719
29,30,122338.48,1896.23,0,0,23232,23232,7125.0,90582,NaN,NaN,1401
30,31,129292.63,1932.68,0,0,25624,25624,3330.0,99992,NaN,NaN,348
31,32,131070.01,1966.86,0,0,25979,25979,4467.0,99792,NaN,NaN,824
32,33,132964.01,1948.36,0,0,25524,25524,4287.0,101381,NaN,NaN,1773
33,34,132722.66,1911.43,0,0,26045,26045,5430.0,99476,NaN,NaN,1773
34,35,116272.00,1778.36,0,0,22888,22888,4211.0,88426,NaN,NaN,748
35,36,124971.00,1875.53,0,0,26298,26298,5662.0,92907,NaN,NaN,100
36,37,133955.00,1985.11,0,0,27177,27177,5131.0,101155,NaN,NaN,493
37,38,130549.30,1960.55,0,0,26903,26903,4476.0,97431,NaN,NaN,1740
38,39,131818.78,2019.43,0,0,28376,28376,5862.0,95293,NaN,NaN,2287
39,40,115369.18,1823.85,0,0,25080,25080,5081.0,84487,NaN,NaN,716
40,41,127170.72,1928.58,0,0,26978,26978,4824.0,94523,NaN,NaN,846
41,42,127623.08,1832.75,0,0,25964,25964,4744.0,94515,NaN,NaN,2398
42,43,134073.92,1901.85,0,0,28793,28793,5615.0,95982,NaN,NaN,3685
43,44,125501.48,1896.90,0,0,27318,27318,5110.0,92186,NaN,NaN,889
44,45,116152.83,1780.83,0,0,24254,24254,4804.0,85645,NaN,NaN,1450
45,46,120669.77,1731.20,0,0,24987,24987,5191.0,89697,NaN,NaN,796
46,47,122295.51,1765.83,0,0,25101,25101,5485.0,90117,NaN,NaN,1593
47,48,121318.03,1783.36,0,0,23996,23996,5091.0,90894,NaN,NaN,1337
48,49,123920.31,1731.93,0,0,25100,25100,5701.0,90887,NaN,NaN,2202
49,50,124976.25,1835.76,0,0,26344,26344,6082.0,91554,NaN,NaN,995
50,51,126842.01,1812.96,0,0,24106,24106,6313.0,92175,NaN,NaN,4248
51,52,125271.19,1850.80,0,0,24233,24233,6038.0,89845,NaN,NaN,5156

### Data wrangling adding WeekYr and WeekNum

In [75]:
def year (series):
    if series <= 8:
        return 2019
    else:
        return 2020

CFA['WeekYr']= CFA['Week'].apply(year)

In [76]:
CFA.tail()

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering,WeekYr
47,48,121318.03,1783.36,0,0,23996,23996,5091.0,90894,NaN,NaN,1337,2020
48,49,123920.31,1731.93,0,0,25100,25100,5701.0,90887,NaN,NaN,2202,2020
49,50,124976.25,1835.76,0,0,26344,26344,6082.0,91554,NaN,NaN,995,2020
50,51,126842.01,1812.96,0,0,24106,24106,6313.0,92175,NaN,NaN,4248,2020
51,52,125271.19,1850.80,0,0,24233,24233,6038.0,89845,NaN,NaN,5156,2020

In [77]:
def wk (series):
    if series <= 2019:
        return 44
    else:
        return -8
    
CFA['WeekF'] = CFA['WeekYr'].apply(wk)
CFA['WeekNum'] = CFA["Week"] + CFA['WeekF']

In [78]:
CFA

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering,WeekYr,WeekF,WeekNum
0,1,125836.82,2018.28,7434,1238,6958,15630,NaN,76008,12935.0,19067.0,2197,2019,44,45
1,2,126169.87,1931.96,8179,1016,7888,17083,NaN,74817,13882.0,18766.0,1621,2019,44,46
2,3,130949.97,1961.31,9309,1087,7695,18091,NaN,79235,12819.0,18002.0,2801,2019,44,47
3,4,98556.80,1616.51,5851,454,5438,11743,NaN,60434,10312.0,14509.0,1557,2019,44,48
4,5,128648.25,1944.40,7829,871,7137,15837,NaN,78364,14418.0,17617.0,2411,2019,44,49
5,6,134611.88,1987.98,8060,1159,8087,17306,NaN,81339,15743.0,17759.0,2465,2019,44,50
6,7,137931.66,2058.60,9080,999,7316,17395,NaN,82617,15442.0,17973.0,4504,2019,44,51
7,8,98336.56,1475.50,6180,625,5300,12105,NaN,58439,10728.0,15119.0,1946,2019,44,52
8,9,111412.63,1739.10,6525,1036,5815,13376,NaN,65663,11527.0,19590.0,1257,2020,-8,1
9,10,120144.74,1846.63,7646,1015,6812,15473,NaN,75033,10578.0,16980.0,2081,2020,-8,2
10,11,120890.11,1801.21,7559,1432,6835,15826,NaN,72163,13107.0,18728.0,1065,2020,-8,3
11,12,124143.74,1855.66,8324,1691,7755,17770,NaN,70682,11939.0,19062.0,4690,2020,-8,4
12,13,122794.31,1846.58,6449,1264,8852,16565,1801.0,72919,12409.0,17226.0,1875,2020,-8,5
13,14,117421.37,1789.86,5586,1192,7602,14380,2022.0,72110,12088.0,15032.0,1791,2020,-8,6
14,15,118343.59,1793.33,5971,883,6958,13812,1639.0,73035,12233.0,16059.0,1559,2020,-8,7
15,16,122036.56,1814.68,6229,1713,8263,16205,1892.0,72372,12213.0,18075.0,1280,2020,-8,8
16,17,125188.19,1855.68,6426,1567,7750,15743,2010.0,75848,12769.0,17180.0,1640,2020,-8,9
17,18,128334.95,1956.06,6677,1406,8419,16502,2377.0,74775,14226.0,16738.0,3718,2020,-8,10
18,19,127679.69,1897.00,6932,1230,8687,16849,2328.0,78163,12541.0,15314.0,2486,2020,-8,11
19,20,100793.26,1790.56,148,0,13383,13531,1934.0,85237,NaN,NaN,90,2020,-8,12
20,21,88279.11,1357.32,0,0,12884,12884,2230.0,72932,NaN,NaN,243,2020,-8,13
21,22,90827.94,1388.55,0,0,16095,16095,2727.0,71890,NaN,NaN,116,2020,-8,14
22,23,94278.31,1378.33,0,0,18836,18836,3254.0,71400,NaN,NaN,793,2020,-8,15
23,24,103772.89,1499.16,0,0,20381,20381,4247.0,78919,NaN,NaN,245,2020,-8,16
24,25,106622.80,1849.18,0,0,20985,20985,4771.0,80194,NaN,NaN,673,2020,-8,17
25,26,116115.88,1800.25,0,0,23454,23454,4913.0,86941,NaN,NaN,808,2020,-8,18
26,27,119367.33,1839.55,0,0,22477,22477,4900.0,91275,NaN,NaN,714,2020,-8,19
27,28,123036.22,1845.00,0,0,25137,25137,4072.0,93427,NaN,NaN,400,2020,-8,20
28,29,149466.31,1920.10,0,0,33563,33563,8749.0,105435,NaN,NaN,1719,2020,-8,21
29,30,122338.48,1896.23,0,0,23232,23232,7125.0,90582,NaN,NaN,1401,2020,-8,22
30,31,129292.63,1932.68,0,0,25624,25624,3330.0,99992,NaN,NaN,348,2020,-8,23
31,32,131070.01,1966.86,0,0,25979,25979,4467.0,99792,NaN,NaN,824,2020,-8,24
32,33,132964.01,1948.36,0,0,25524,25524,4287.0,101381,NaN,NaN,1773,2020,-8,25
33,34,132722.66,1911.43,0,0,26045,26045,5430.0,99476,NaN,NaN,1773,2020,-8,26
34,35,116272.00,1778.36,0,0,22888,22888,4211.0,88426,NaN,NaN,748,2020,-8,27
35,36,124971.00,1875.53,0,0,26298,26298,5662.0,92907,NaN,NaN,100,2020,-8,28
36,37,133955.00,1985.11,0,0,27177,27177,5131.0,101155,NaN,NaN,493,2020,-8,29
37,38,130549.30,1960.55,0,0,26903,26903,4476.0,97431,NaN,NaN,1740,2020,-8,30
38,39,131818.78,2019.43,0,0,28376,28376,5862.0,95293,NaN,NaN,2287,2020,-8,31
39,40,115369.18,1823.85,0,0,25080,25080,5081.0,84487,NaN,NaN,716,2020,-8,32
40,41,127170.72,1928.58,0,0,26978,26978,4824.0,94523,NaN,NaN,846,2020,-8,33
41,42,127623.08,1832.75,0,0,25964,25964,4744.0,94515,NaN,NaN,2398,2020,-8,34
42,43,134073.92,1901.85,0,0,28793,28793,5615.0,95982,NaN,NaN,3685,2020,-8,35
43,44,125501.48,1896.90,0,0,27318,27318,5110.0,92186,NaN,NaN,889,2020,-8,36
44,45,116152.83,1780.83,0,0,24254,24254,4804.0,85645,NaN,NaN,1450,2020,-8,37
45,46,120669.77,1731.20,0,0,24987,24987,5191.0,89697,NaN,NaN,796,2020,-8,38
46,47,122295.51,1765.83,0,0,25101,25101,5485.0,90117,NaN,NaN,1593,2020,-8,39
47,48,121318.03,1783.36,0,0,23996,23996,5091.0,90894,NaN,NaN,1337,2020,-8,40
48,49,123920.31,1731.93,0,0,25100,25100,5701.0,90887,NaN,NaN,2202,2020,-8,41
49,50,124976.25,1835.76,0,0,26344,26344,6082.0,91554,NaN,NaN,995,2020,-8,42
50,51,126842.01,1812.96,0,0,24106,24106,6313.0,92175,NaN,NaN,4248,2020,-8,43
51,52,125271.19,1850.80,0,0,24233,24233,6038.0,89845,NaN,NaN,5156,2020,-8,44

In [79]:
CFA.drop(['WeekF'],axis=1, inplace=True)
CFA.tail()

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering,WeekYr,WeekNum
47,48,121318.03,1783.36,0,0,23996,23996,5091.0,90894,NaN,NaN,1337,2020,40
48,49,123920.31,1731.93,0,0,25100,25100,5701.0,90887,NaN,NaN,2202,2020,41
49,50,124976.25,1835.76,0,0,26344,26344,6082.0,91554,NaN,NaN,995,2020,42
50,51,126842.01,1812.96,0,0,24106,24106,6313.0,92175,NaN,NaN,4248,2020,43
51,52,125271.19,1850.80,0,0,24233,24233,6038.0,89845,NaN,NaN,5156,2020,44

In [82]:
CFA['Productivity'] = CFA['Sales'] / CFA['HoursUsed']
CFA.head()

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering,WeekYr,WeekNum,Productivity
0,1,125836.82,2018.28,7434,1238,6958,15630,NaN,76008,12935.0,19067.0,2197,2019,45,62.348544
1,2,126169.87,1931.96,8179,1016,7888,17083,NaN,74817,13882.0,18766.0,1621,2019,46,65.306668
2,3,130949.97,1961.31,9309,1087,7695,18091,NaN,79235,12819.0,18002.0,2801,2019,47,66.766585
3,4,98556.80,1616.51,5851,454,5438,11743,NaN,60434,10312.0,14509.0,1557,2019,48,60.968877
4,5,128648.25,1944.40,7829,871,7137,15837,NaN,78364,14418.0,17617.0,2411,2019,49,66.163469

In [85]:
def division (series):
    if series <= 19:
        return 'Before'
    if series >= 25:
        return 'After'
    else:
        return 'During'
    
CFA['Time'] = CFA['Week'].apply(division)
CFA

,Week,Sales,HoursUsed,MobCO,MobDI,MobDT,Mobile Sales,3rdParty,NormDT,CarryO,DineIn,Catering,WeekYr,WeekNum,Productivity,Time
0,1,125836.82,2018.28,7434,1238,6958,15630,NaN,76008,12935.0,19067.0,2197,2019,45,62.348544,Before
1,2,126169.87,1931.96,8179,1016,7888,17083,NaN,74817,13882.0,18766.0,1621,2019,46,65.306668,Before
2,3,130949.97,1961.31,9309,1087,7695,18091,NaN,79235,12819.0,18002.0,2801,2019,47,66.766585,Before
3,4,98556.80,1616.51,5851,454,5438,11743,NaN,60434,10312.0,14509.0,1557,2019,48,60.968877,Before
4,5,128648.25,1944.40,7829,871,7137,15837,NaN,78364,14418.0,17617.0,2411,2019,49,66.163469,Before
5,6,134611.88,1987.98,8060,1159,8087,17306,NaN,81339,15743.0,17759.0,2465,2019,50,67.712894,Before
6,7,137931.66,2058.60,9080,999,7316,17395,NaN,82617,15442.0,17973.0,4504,2019,51,67.002652,Before
7,8,98336.56,1475.50,6180,625,5300,12105,NaN,58439,10728.0,15119.0,1946,2019,52,66.646262,Before
8,9,111412.63,1739.10,6525,1036,5815,13376,NaN,65663,11527.0,19590.0,1257,2020,1,64.063383,Before
9,10,120144.74,1846.63,7646,1015,6812,15473,NaN,75033,10578.0,16980.0,2081,2020,2,65.061620,Before
10,11,120890.11,1801.21,7559,1432,6835,15826,NaN,72163,13107.0,18728.0,1065,2020,3,67.116055,Before
11,12,124143.74,1855.66,8324,1691,7755,17770,NaN,70682,11939.0,19062.0,4690,2020,4,66.900046,Before
12,13,122794.31,1846.58,6449,1264,8852,16565,1801.0,72919,12409.0,17226.0,1875,2020,5,66.498235,Before
13,14,117421.37,1789.86,5586,1192,7602,14380,2022.0,72110,12088.0,15032.0,1791,2020,6,65.603662,Before
14,15,118343.59,1793.33,5971,883,6958,13812,1639.0,73035,12233.0,16059.0,1559,2020,7,65.990972,Before
15,16,122036.56,1814.68,6229,1713,8263,16205,1892.0,72372,12213.0,18075.0,1280,2020,8,67.249631,Before
16,17,125188.19,1855.68,6426,1567,7750,15743,2010.0,75848,12769.0,17180.0,1640,2020,9,67.462165,Before
17,18,128334.95,1956.06,6677,1406,8419,16502,2377.0,74775,14226.0,16738.0,3718,2020,10,65.608903,Before
18,19,127679.69,1897.00,6932,1230,8687,16849,2328.0,78163,12541.0,15314.0,2486,2020,11,67.306110,Before
19,20,100793.26,1790.56,148,0,13383,13531,1934.0,85237,NaN,NaN,90,2020,12,56.291473,During
20,21,88279.11,1357.32,0,0,12884,12884,2230.0,72932,NaN,NaN,243,2020,13,65.039276,During
21,22,90827.94,1388.55,0,0,16095,16095,2727.0,71890,NaN,NaN,116,2020,14,65.412077,During
22,23,94278.31,1378.33,0,0,18836,18836,3254.0,71400,NaN,NaN,793,2020,15,68.400390,During
23,24,103772.89,1499.16,0,0,20381,20381,4247.0,78919,NaN,NaN,245,2020,16,69.220690,During
24,25,106622.80,1849.18,0,0,20985,20985,4771.0,80194,NaN,NaN,673,2020,17,57.659503,After
25,26,116115.88,1800.25,0,0,23454,23454,4913.0,86941,NaN,NaN,808,2020,18,64.499864,After
26,27,119367.33,1839.55,0,0,22477,22477,4900.0,91275,NaN,NaN,714,2020,19,64.889419,After
27,28,123036.22,1845.00,0,0,25137,25137,4072.0,93427,NaN,NaN,400,2020,20,66.686298,After
28,29,149466.31,1920.10,0,0,33563,33563,8749.0,105435,NaN,NaN,1719,2020,21,77.842982,After
29,30,122338.48,1896.23,0,0,23232,23232,7125.0,90582,NaN,NaN,1401,2020,22,64.516688,After
30,31,129292.63,1932.68,0,0,25624,25624,3330.0,99992,NaN,NaN,348,2020,23,66.898105,After
31,32,131070.01,1966.86,0,0,25979,25979,4467.0,99792,NaN,NaN,824,2020,24,66.639217,After
32,33,132964.01,1948.36,0,0,25524,25524,4287.0,101381,NaN,NaN,1773,2020,25,68.244067,After
33,34,132722.66,1911.43,0,0,26045,26045,5430.0,99476,NaN,NaN,1773,2020,26,69.436317,After
34,35,116272.00,1778.36,0,0,22888,22888,4211.0,88426,NaN,NaN,748,2020,27,65.381588,After
35,36,124971.00,1875.53,0,0,26298,26298,5662.0,92907,NaN,NaN,100,2020,28,66.632365,After
36,37,133955.00,1985.11,0,0,27177,27177,5131.0,101155,NaN,NaN,493,2020,29,67.479888,After
37,38,130549.30,1960.55,0,0,26903,26903,4476.0,97431,NaN,NaN,1740,2020,30,66.588100,After
38,39,131818.78,2019.43,0,0,28376,28376,5862.0,95293,NaN,NaN,2287,2020,31,65.275241,After
39,40,115369.18,1823.85,0,0,25080,25080,5081.0,84487,NaN,NaN,716,2020,32,63.255849,After
40,41,127170.72,1928.58,0,0,26978,26978,4824.0,94523,NaN,NaN,846,2020,33,65.940080,After
41,42,127623.08,1832.75,0,0,25964,25964,4744.0,94515,NaN,NaN,2398,2020,34,69.634746,After
42,43,134073.92,1901.85,0,0,28793,28793,5615.0,95982,NaN,NaN,3685,2020,35,70.496580,After
43,44,125501.48,1896.90,0,0,27318,27318,5110.0,92186,NaN,NaN,889,2020,36,66.161358,After
44,45,116152.83,1780.83,0,0,24254,24254,4804.0,85645,NaN,NaN,1450,2020,37,65.223985,After
45,46,120669.77,1731.20,0,0,24987,24987,5191.0,89697,NaN,NaN,796,2020,38,69.702963,After
46,47,122295.51,1765.83,0,0,25101,25101,5485.0,90117,NaN,NaN,1593,2020,39,69.256672,After
47,48,121318.03,1783.36,0,0,23996,23996,5091.0,90894,NaN,NaN,1337,2020,40,68.027785,After
48,49,123920.31,1731.93,0,0,25100,25100,5701.0,90887,NaN,NaN,2202,2020,41,71.550415,After
49,50,124976.25,1835.76,0,0,26344,26344,6082.0,91554,NaN,NaN,995,2020,42,68.078752,After
50,51,126842.01,1812.96,0,0,24106,24106,6313.0,92175,NaN,NaN,4248,2020,43,69.964042,After
51,52,125271.19,1850.80,0,0,24233,24233,6038.0,89845,NaN,NaN,5156,2020,44,67.684888,After

In [86]:
CFA.to_excel('CFA_data.xlsx')